title: womxnbuild
author: womxnbuild
email: womenbuildthings@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Welcome to WomxnBuild's Blog! This is your space - to build, share and 
  explore the world of a builder on the web, and I am here to tell your stories! 💕 

# social links
twitter_username: womxnbuild # DO NOT include the @ character, or else the build will fail!
github_username:  womxnbuild # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
